#!/usr/bin/env python

RESPONSE_OK = 200
RESPONSE_CREATED = 201

RESPONSE_BAD_REQUEST = 400
RESPONSE_UNAUTHORIZED = 401
RESPONSE_FORBIDDEN = 403
RESPONSE_NOT_FOUND = 404
RESPONSE_METHOD_NOT_ALLOWED = 405
RESPONSE_NOT_ACCEPTABLE = 406
RESPONSE_CONFLICT = 409
RESPONSE_GONE = 412

RESPONSE_SERVER_ERROR = 500


ERROR_OK = 0
ERROR_INVALID_DATA = 1
ERROR_NO_DATA = 2
ERROR_NOT_ALLOWED = 3
ERROR_NO_SUCH_MODULE = 4
ERROR_DB_ERROR = 5
ERROR_NOT_AUTHORIZED = 6
ERROR_NOT_FOUND = 7
